# Generated by Django 5.2.8 on 2025-12-02 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('abbreviation', models.CharField(max_length=2, verbose_name='Abbreviation')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countrys',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FederativeUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('abbreviation', models.CharField(max_length=2, verbose_name='Abbreviation')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='federativeunit_country_country', to='address.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'FederativeUnit',
                'verbose_name_plural': 'FederativeUnits',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('federative_unit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='city_federativeunit_federative_unit', to='address.federativeunit', verbose_name='Federative Unit')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Neighbordhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='neighbordhood_city_city', to='address.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Neighbordhood',
                'verbose_name_plural': 'Neighbordhoods',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('street_name', models.CharField(max_length=100, verbose_name='Street Name')),
                ('number', models.PositiveIntegerField(verbose_name='Number')),
                ('postal_code', models.CharField(verbose_name='Postal Code')),
                ('complements', models.TextField(blank=True, null=True, verbose_name='Complements')),
                ('neighbordhood', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='address_neighbordhood_neighbordhood', to='address.neighbordhood', verbose_name='Neighbordhood')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'ordering': ['-id'],
            },
        ),
    ]
