# Generated by Django 5.2.8 on 2025-12-05 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='abbreviation',
            field=models.CharField(max_length=3, verbose_name='Abbreviation'),
        ),
    ]
