# Generated by Django 5.2.8 on 2025-12-06 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_country_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='last_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modification'),
        ),
        migrations.AddField(
            model_name='address',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registration Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='last_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modification'),
        ),
        migrations.AddField(
            model_name='city',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registration Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='last_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modification'),
        ),
        migrations.AddField(
            model_name='country',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registration Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='federativeunit',
            name='last_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modification'),
        ),
        migrations.AddField(
            model_name='federativeunit',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registration Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='neighbordhood',
            name='last_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modification'),
        ),
        migrations.AddField(
            model_name='neighbordhood',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registration Date'),
            preserve_default=False,
        ),
    ]
