# Generated by Django 5.2.8 on 2025-12-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='customusers',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
