# Generated by Django 5.2.8 on 2025-12-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customusers_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
