# Generated by Django 5.2.8 on 2025-12-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customusers_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='customusers',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into the admin site.', verbose_name='Admin Status'),
        ),
        migrations.AddField(
            model_name='customusers',
            name='is_admin_ti',
            field=models.BooleanField(default=False, help_text='Designates that the user has access to IT permissions assignment management.', verbose_name='TI Admin Status'),
        ),
    ]
