# Generated by Django 5.2.8 on 2025-12-10 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customusers_is_staff_customusers_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusers',
            options={'ordering': ['-id'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
