# Generated by Django 5.2.8 on 2025-11-27 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70, verbose_name='Full Name')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('cellphone', models.CharField(blank=True, max_length=11, null=True, verbose_name='Cellphone')),
                ('oab', models.CharField(max_length=50, verbose_name='Full Name')),
                ('oab_status', models.CharField(max_length=50, verbose_name='Full Name')),
                ('specialty', models.CharField(max_length=50, verbose_name='Full Name')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='employee_role_role', to='employee.role', verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['full_name'],
            },
        ),
    ]
