# Generated by Django 5.2.8 on 2025-12-05 01:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('employee', '0002_employee_address_employee_is_active_role_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='employee_address_address', to='address.address', verbose_name='Address'),
        ),
    ]
