# Generated by Django 5.2.8 on 2025-12-06 16:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modification'),
        ),
        migrations.AddField(
            model_name='employee',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registration Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='last_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modification'),
        ),
        migrations.AddField(
            model_name='role',
            name='registration',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Registration Date'),
            preserve_default=False,
        ),
    ]
