# Generated by Django 5.2.8 on 2025-12-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_last_modification_employee_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_system_user',
            field=models.BooleanField(default=False, verbose_name='Is System User'),
        ),
    ]
